// Client-side mirror of matchRoleToLibrary (server-side at
// supabase/functions/_shared/cv-templates/sector-mapping.ts:156).
//
// Used by StepRoleSkills to suggest skills for an experience based on
// its title — "Customer Success Specialist – VIP Team" matches the
// canonical role "Customer Success Specialist" via prefix-match and
// returns its core + secondary skills as suggestions.
//
// Source data: src/lib/roleSkillsGenerated.json — generated by
// scripts/regen-role-skills.mjs from 00_role_library.ts + 04_role_skill_mapping.ts.
// 183 roles, 170 with skill mappings. Re-run the generator after edits
// to those library files.
//
// Strategy chain mirrors the server-side matcher:
//   1. exact id match
//   2. normalized title or standardized_title match
//   3. alternate_titles match
//   4. paren-stripped retry of 2-3
//   5. seniority-stripped retry of 2-3
//   6. slash-split retry on each side
//   7. prefix-match (NEW — handles "Customer Success Specialist – VIP Team"
//      → matches "Customer Success Specialist" at length 3 of 5 tokens).
//      Gated by ≥2 tokens after stripping to avoid short-title false positives.

import roleData from "./roleSkillsGenerated.json";

const ROLES = roleData.roles || [];

const normalize = (s) => String(s || "").toLowerCase().replace(/[\s_\-—–]+/g, " ").trim();
const stripParens = (s) => String(s || "").replace(/\s*\([^)]*\)\s*/g, " ").trim();

// Same seniority prefixes the server-side matcher strips. Conservative —
// only well-known seniority words at the START.
const SENIORITY_PREFIX_RE = /^(senior|sr\.?|junior|jr\.?|lead|principal|staff|head of|chief)\s+/i;
const stripSeniority = (s) => String(s || "").replace(SENIORITY_PREFIX_RE, "").trim();

function matchTitle(norm) {
  return ROLES.find((r) => r.title && normalize(r.title) === norm);
}
function matchAlternate(norm) {
  return ROLES.find((r) => Array.isArray(r.alternate_titles) && r.alternate_titles.some((alt) => normalize(alt) === norm));
}

/**
 * Match a free-text role title to the canonical role library.
 * Returns { role, via } or null. `via` enums:
 *   id | title | alternate_title | title_stripped_parens | alternate_stripped_parens
 *   | title_stripped_seniority | alternate_stripped_seniority
 *   | title_slash_split | alternate_slash_split | title_prefix
 */
export function matchRoleToLibrary(rawTitle) {
  const t = String(rawTitle || "").trim();
  if (!t) return null;
  const tn = normalize(t);

  // Strategy 1 — exact id
  const byId = ROLES.find((r) => r.id === t);
  if (byId) return { role: byId, via: "id" };

  // Strategy 2 — normalized title
  const m2 = matchTitle(tn);
  if (m2) return { role: m2, via: "title" };

  // Strategy 3 — alternate_titles
  const m3 = matchAlternate(tn);
  if (m3) return { role: m3, via: "alternate_title" };

  // Strategy 4 — strip parens
  const noParens = normalize(stripParens(t));
  if (noParens && noParens !== tn) {
    const m4t = matchTitle(noParens);
    if (m4t) return { role: m4t, via: "title_stripped_parens" };
    const m4a = matchAlternate(noParens);
    if (m4a) return { role: m4a, via: "alternate_stripped_parens" };
  }

  // Strategy 5 — strip seniority
  const noSeniority = normalize(stripSeniority(stripParens(t)));
  if (noSeniority && noSeniority !== noParens) {
    const m5t = matchTitle(noSeniority);
    if (m5t) return { role: m5t, via: "title_stripped_seniority" };
    const m5a = matchAlternate(noSeniority);
    if (m5a) return { role: m5a, via: "alternate_stripped_seniority" };
  }

  // Strategy 6 — slash-split
  if (noSeniority.includes("/")) {
    for (const side of noSeniority.split("/").map((s) => s.trim()).filter(Boolean)) {
      const m6t = matchTitle(side);
      if (m6t) return { role: m6t, via: "title_slash_split" };
      const m6a = matchAlternate(side);
      if (m6a) return { role: m6a, via: "alternate_slash_split" };
    }
  }

  // Strategy 7 — prefix match (NEW)
  // For titles like "Customer Success Specialist – VIP Team", try
  // progressively shorter token prefixes. Gated by ≥2 tokens after
  // seniority+paren stripping to avoid "PM" → matching any role
  // starting with PM. Walks longest-first so the most specific role wins.
  const tokens = noSeniority.split(/\s+/).filter(Boolean);
  if (tokens.length >= 2) {
    for (let len = tokens.length - 1; len >= 2; len--) {
      const prefix = tokens.slice(0, len).join(" ");
      const m7t = matchTitle(prefix);
      if (m7t) return { role: m7t, via: "title_prefix" };
      const m7a = matchAlternate(prefix);
      if (m7a) return { role: m7a, via: "alternate_prefix" };
    }
  }

  return null;
}

/**
 * Suggest skills for an experience title. Returns:
 *   { roleTitle, via, skillIds }  if a confident match exists
 *   null                          if no match (no suggestions shown)
 *
 * "Confident" = `via` is exact-ish (NOT raw fuzzy). Currently all 7
 * strategies are accepted because each enforces structural matching
 * (whole-word, exact-after-strip, etc.). Adjust the acceptedVias set
 * if real-world usage shows false positives from any strategy.
 *
 * skillIds = core_skills ∪ secondary_skills (differentiator skills
 * are too specialized for onboarding suggestions and excluded).
 */
const ACCEPTED_VIAS = new Set([
  "id", "title", "alternate_title",
  "title_stripped_parens", "alternate_stripped_parens",
  "title_stripped_seniority", "alternate_stripped_seniority",
  "title_slash_split", "alternate_slash_split",
  "title_prefix", "alternate_prefix",
]);

export function suggestSkillsForTitle(rawTitle) {
  const matched = matchRoleToLibrary(rawTitle);
  if (!matched) return null;
  if (!ACCEPTED_VIAS.has(matched.via)) return null;
  const { role, via } = matched;
  const skillIds = [
    ...(Array.isArray(role.core_skills) ? role.core_skills : []),
    ...(Array.isArray(role.secondary_skills) ? role.secondary_skills : []),
  ];
  // Dedupe
  const uniq = [...new Set(skillIds)];
  if (uniq.length === 0) return null;
  return { roleTitle: role.title, via, skillIds: uniq };
}
