// Due-date utilities for tasks.
//
// 2026-05-21: Removed the priority-based auto-fallback. Tasks generated by
// the LLM no longer get a synthetic due date when the LLM doesn't provide
// one — "no date = no pressure" is the new product rule. Users explicitly
// set dates via the UI per task. resolveDueDate now returns null when the
// LLM value is missing or invalid, instead of falling back to N days from
// now. defaultDueDateFor was removed for the same reason.

export function validateDueDate(s) {
  if (!s) return null;
  const d = new Date(s);
  if (Number.isNaN(d.getTime())) return null;
  const now = Date.now();
  if (d.getTime() < now - 86400000) return null;          // not >1 day in the past
  if (d.getTime() > now + 180 * 86400000) return null;    // not >180 days in the future
  return d.toISOString();
}

// Returns a valid ISO date string OR null. Callers should treat null as
// "no due date" and either omit the column or write null to the DB —
// either way the resulting row reflects "user has not set a date".
export function resolveDueDate(llmValue) {
  return validateDueDate(llmValue);
}
